### ISSUE TITLE
automatically deploy pkgdown website

### ISSUE THREAD

**Issue by czeildi** [ropenscilabs/ropsec#18]
https://pkgdown.r-lib.org/

**Comment by czeildi** [comment]
Hey @hrbrmstr 

could you provide admin rights to me in this repository, or set up github pages for the docs folder?

I currently would like to create a pkgdown website but do not have the rights to do that.

Thanks a lot!

**Comment by czeildi** [comment]
Hi @maelle, sorry to bother you again, but could you help me out here?

could you provide admin rights to me in this repository, or set up github pages for the docs folder?

I currently would like to create a pkgdown website but do not have the rights to do that.

 I am not sure who has actually admin rights but neither Kara nor myself have and we worked on this repo the most (still only a little) recently.

**Comment by maelle** [comment]
:wave: @czeildi! Now both you and Kara are admin. If I ever miss a notification, which can happen to anyone, please don't hesitate to ping me in Slack!

Regarding the `pkgdown` setup, if you want to deploy it from Travis (so that it'd get built with each push to master, in a gh-pages branch) have a look at https://github.com/ropenscilabs/tic and https://github.com/ropenscilabs/travis in particular if you run `usethis::use_pkgdown()` and then `travis::use_tic()`, it'd help you with deploy key/tokens etc. In https://github.com/lockedata/cransays/blob/master/tic.R#L12 I just had to add a condition to only deploy from master.

**Comment by czeildi** [comment]
thanks a lot for the detailed instructions!
